name: "Trash Build"
description: "Builds a site using the Trash SSG."
inputs:
  go-version:
    description: "Go version to use"
    required: false
    default: "^1.25.0"
  build-path:
    description: "Path to the site root"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Cache Trash Binary
      id: cache-trash
      uses: actions/cache@v4
      with:
        path: ~/go/bin/trash
        key: ${{ runner.os }}-trash-bin-v1

    - name: Install Trash
      if: steps.cache-trash.outputs.cache-hit != 'true'
      shell: bash
      run: go install github.com/zeozeozeo/trash@latest

    - name: Build Site
      shell: bash
      run: |
        TRASH_NO_SANDBOX=1 $(go env GOPATH)/bin/trash build ${{ inputs.build-path }}

branding:
  icon: "trash-2"
  color: "gray-dark"
